#!/usr/bin/env node
/**
 * Generate supabase/seed.sql from the canonical src/data/*.js files.
 *
 * Usage:  npm run seed:build
 *
 * This keeps the DB seed in lockstep with the offline-fallback data so there's
 * a single source of truth. Paste the generated SQL into the Supabase SQL
 * Editor once (after schema.sql) to populate your tables.
 */
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'supabase/seed.sql');

const { default: projects } = await import('../src/data/projects.js');
const { default: experience } = await import('../src/data/experience.js');
const { default: skills } = await import('../src/data/skills.js');
const { default: certifications } = await import('../src/data/certifications.js');
const { default: profile } = await import('../src/data/profile.js');

// --- SQL literal helpers ---------------------------------------------------
const q = (v) => (v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const bool = (v) => (v ? 'true' : 'false');
const textArr = (arr) =>
  `array[${(arr || []).map((s) => q(s)).join(', ')}]::text[]`;
const jsonb = (obj) => `${q(JSON.stringify(obj))}::jsonb`;

const lines = [];
lines.push('-- AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.');
lines.push('-- Run AFTER schema.sql. Idempotent: truncates each table first.');
lines.push('');

// projects
lines.push('truncate table public.projects restart identity cascade;');
lines.push(
  'insert into public.projects (title, description, tech, category, github, demo, featured, has_interactive_demo, sort_order) values',
);
lines.push(
  projects
    .map(
      (p, i) =>
        `  (${q(p.title)}, ${q(p.description)}, ${textArr(p.tech)}, ${q(
          p.category,
        )}, ${q(p.github)}, ${q(p.demo)}, ${bool(p.featured)}, ${bool(
          p.hasInteractiveDemo,
        )}, ${i})`,
    )
    .join(',\n') + ';',
);
lines.push('');

// experience
lines.push('truncate table public.experience restart identity cascade;');
lines.push(
  'insert into public.experience (role, company, duration, location, client, highlights, tech_ai, tech, sort_order) values',
);
lines.push(
  experience
    .map(
      (e, i) =>
        `  (${q(e.role)}, ${q(e.company)}, ${q(e.duration)}, ${q(
          e.location,
        )}, ${q(e.client)}, ${textArr(e.highlights)}, ${textArr(
          e.techAI,
        )}, ${textArr(e.tech)}, ${i})`,
    )
    .join(',\n') + ';',
);
lines.push('');

// skill_groups
lines.push('truncate table public.skill_groups restart identity cascade;');
lines.push('insert into public.skill_groups (category, items, sort_order) values');
lines.push(
  skills
    .map((g, i) => `  (${q(g.category)}, ${jsonb(g.items)}, ${i})`)
    .join(',\n') + ';',
);
lines.push('');

// certifications
lines.push('truncate table public.certifications restart identity cascade;');
lines.push(
  'insert into public.certifications (title, issuer, date, detail, credential_url, sort_order) values',
);
lines.push(
  certifications
    .map(
      (c, i) =>
        `  (${q(c.title)}, ${q(c.issuer)}, ${q(c.date)}, ${q(c.detail)}, ${q(
          c.credentialUrl,
        )}, ${i})`,
    )
    .join(',\n') + ';',
);
lines.push('');

// profile (single row, pinned by the `singleton` column)
lines.push('truncate table public.profile restart identity cascade;');
lines.push(
  'insert into public.profile (singleton, name, title, location, email, phone, linkedin, linkedin_url, github, github_url, summary, hero, about, highlights, education) values',
);
lines.push(
  `  (true, ${q(profile.name)}, ${q(profile.title)}, ${q(profile.location)}, ${q(
    profile.email,
  )}, ${q(profile.phone)}, ${q(profile.linkedin)}, ${q(profile.linkedinUrl)}, ${q(
    profile.github,
  )}, ${q(profile.githubUrl)}, ${q(profile.summary)}, ${jsonb(profile.hero)}, ${jsonb(
    profile.about,
  )}, ${jsonb(profile.highlights)}, ${jsonb(profile.education)});`,
);
lines.push('');

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, lines.join('\n'));
console.log(`✓ Wrote ${path.relative(ROOT, OUT)}`);
console.log(
  `  ${projects.length} projects · ${experience.length} experience · ${skills.length} skill groups · ${certifications.length} certs · 1 profile`,
);
